/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        xsm: "820px",
        xlg: "1060px",
      },
      height: {
        mobileheader: "var(--header-mobile-height)",
        header: "var(--header-height)",
      },
      colors: {
        bg: {
          forum: "black",
          post: "#1b1f23", // Dark background for posts in the forum
        },
        forum: {
          heading: "var(--forum-heading)",
          heading2: "var(--forum-createpost-heading)",
          subheading: "var(--forum-subheading)",
          subheading2: "var(--forum-subheading2)",
        },
        bglinkedin: "#f4f2ee",
        sidebar: {
          bg: "var(--sidebar-bg)",
          group: "var(--sidebar-group-bg)",
          text: "var(--sidebar-text)",
          border: "var(--sidebar-border2)",
          separator: "var(--sidebar-separator)",
          inputbg: "var(--sidebar-input-bg)",
          inputborder: "var(--sidebar-input-border)",
          inputtext: "var(--sidebar-input-text)",
          inputplaceholder: "var(--sidebar-input-placeholder)",
          inputfocus: "var(--sidebar-input-focus-ring)",
          labeltext: "var(--sidebar-label-text)",
        },
        map:{
          bg: "var(--sidebar-bg)",
          darkerbg: "var(--sidebar-group-bg)",
          text: "var(--sidebar-text)",
          mapcolor: "var(--map-color)",
          legendtext: "var(--legend-text)",
          safety: "var(--safety-color)",
          safety2: "var(--safety-color-2)",
        },
        map:{
          bg: "var(--sidebar-bg)",
          darkerbg: "var(--sidebar-group-bg)",
          text: "var(--sidebar-text)",
          mapcolor: "var(--map-color)",
          legendtext: "var(--legend-text)",
          safety: "var(--safety-color)",
          safety2: "var(--safety-color-2)",
        },
        map:{
          bg: "var(--sidebar-bg)",
          darkerbg: "var(--sidebar-group-bg)",
          text: "var(--sidebar-text)",
          mapcolor: "var(--map-color)",
          legendtext: "var(--legend-text)",
          safety: "var(--safety-color)",
          safety2: "var(--safety-color-2)",
        },
        settingheader: {
          headerheight: "var(--header-height)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    "text-slate-900",
    "text-blue-900",
    "text-blue-400",
    "text-green-400",
    "text-red-400",
    "text-purple-400",
    "text-yellow-400",
    "text-sky-400",
    "text-green-900",
    "text-purple-900",
    "text-red-900",
    "text-yellow-900",
    "text-sky-900",
    "text-slate-600",
    "text-blue-600",
    "text-green-600",
    "text-purple-600",
    "text-red-600",
    "text-yellow-600",
    "text-sky-600",
    "ml-0",
    "ml-8",
    "bg-gray-200",
    "text-white",
    "text-gray-500",
    "hover:bg-blue-900",
    "cursor-pointer",
    "cursor-not-allowed",
    "border-gray-300",
    "text-gray-600",
    "border-transparent",
    "shadow-[0_0_0_2px_rgba(156,163,175,1)]",
    "bg-gray-100",
    "border-green-700",
    "bg-green-700",
    "bg-blue-700",
    "bg-blue-800",
    "ring-blue-300",
    "bg-red-700",
    "bg-red-800",
    "ring-red-300",
    "bg-red-800",
    "items-start",
    "items-center",
    "text-forum-subheading",
    "justify-start",
    "justify-end",
    "ml-8",
    "mr-8",
  ],
};
