# Generated by Django 5.1.6 on 2025-04-23 21:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_issueonlocation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IssueOnLocation",
            new_name="IssueOnLocationReport",
        ),
    ]
