# Generated by Django 5.1.6 on 2025-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_rename_issueonlocation_issueonlocationreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueonlocationreport",
            name="rejection_reason",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
