# Generated by Django 5.1.6 on 2025-04-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_issueonlocationreport_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueonlocationreport",
            name="heatmap_point_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
