# Generated by Django 5.1.6 on 2025-03-18 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_like_like_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_repost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="original_post",
            field=models.ForeignKey(
                blank=True,
                help_text="The original post that this post is reposting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="forum.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="reposted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who reposted this post",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposted_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
