# Generated by Django 5.1.6 on 2025-03-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_post_is_repost_post_original_post_post_reposted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentlike",
            name="like_type",
            field=models.CharField(default="Like", max_length=10, null=True),
        ),
    ]
