# Generated by Django 5.1.6 on 2025-03-20 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_alter_commentlike_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.ForeignKey(
                        help_text="The post that is being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="forum.post",
                    ),
                ),
                (
                    "post_owner_id",
                    models.ForeignKey(
                        help_text="The owner of the post being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_against_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporting_user_id",
                    models.ForeignKey(
                        help_text="The user who is reporting the post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-post_id"],
                "unique_together": {("post_id", "reporting_user_id")},
            },
        ),
    ]
