# Generated by Django 5.1.6 on 2025-03-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_reportpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportpost",
            name="is_repost",
            field=models.BooleanField(default=False),
        ),
    ]
