# Generated by Django 5.1.6 on 2025-03-20 05:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0008_reportpost_is_repost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportpost",
            options={"ordering": ["-post"]},
        ),
        migrations.RenameField(
            model_name="reportpost",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="reportpost",
            old_name="post_owner_id",
            new_name="post_owner",
        ),
        migrations.RenameField(
            model_name="reportpost",
            old_name="reporting_user_id",
            new_name="reporting_user",
        ),
        migrations.AlterUniqueTogether(
            name="reportpost",
            unique_together={("post", "reporting_user")},
        ),
        migrations.AlterField(
            model_name="reportpost",
            name="is_repost",
            field=models.BooleanField(
                default=False, help_text="Indicates if the reported post is a repost"
            ),
        ),
    ]
