# Generated by Django 5.1.6 on 2025-03-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0010_reportcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcomment",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
