# Generated by Django 5.1.6 on 2025-03-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="karma",
            field=models.IntegerField(default=0),
        ),
    ]
