# Generated by Django 5.1.6 on 2025-04-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_reportissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportissue",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
