# Generated by Django 5.1.6 on 2025-04-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_is_banned"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="Firebase Cloud Messaging Token"
            ),
        ),
    ]
