# Generated by Django 5.1.6 on 2025-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.TextField(default="no"),
        ),
    ]
